name:                lyrimport
version:             0.1.0.0
github:              "dmgolubovsky/lyrimport"
license:             BSD3
author:              "Dmitry Golubovsky"
maintainer:          "golubovsky@gmail.com"
copyright:           "none"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dmgolubovsky/lyrimport#readme>

dependencies:
        - base >= 4.7 && < 5
        - getopt-generics
        - filepath
        - directory
        - sqlite-simple == 0.4.18.0
        - text
        - utility-ht
        - strict
        - process
        - split
        - raw-strings-qq
        - containers
        - pureMD5
        - bytestring

library:
  source-dirs: src

executables:
  lyrimport-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lyrimport

tests:
  lyrimport-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lyrimport




